[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[profile.dev]
panic = "abort"
lto = true

[profile.release]
panic = "abort"
lto = true

[build]
rustflags = ["-C", "link-arg=-Tlink.ld"]
target = "i686-kros.json"
