---
name: Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Nasm
        run: sudo apt-get update && sudo apt-get install -y nasm
      - name: Build
        run: cargo build
